[versions]
accompanistPagerIndicators = "0.28.0"
accompanistPager = "0.30.1"
accompanistSwiperefresh = "0.24.8-beta"
android = "10.12.1"
androidGradlePlugin = "8.0.2"
accompanistPermissions = "0.30.1"
accompanistPlaceholderMaterial = "0.24.8-beta"
accompanistSystemuicontroller = "0.24.8-beta"
accompanistNavigationAnimation = "0.30.0"
accompanistNavigationMaterial = "0.33.0-alpha"
activityCompose = "1.7.2"
androidx-lifecycleRuntimeKtx = "2.6.1"
androidxComposeBom = "2023.08.00"
biometricKtx = "1.1.0"
exoplayer = "2.19.0"
firebaseBom = "32.2.2"
androidxComposeCompiler = "1.4.5"
androidxComposeMaterial = "1.1.1"
androidxComposeMaterial3 = "1.1.1"
androidxCore = "1.10.1"
animationGraphics = "1.5.0"
annotationsApi = "6.0.53"
appcompat = "1.6.1"
billingKtx = "6.0.1"
cameraLifecycle = "1.2.3"
cameraView = "1.2.3"
cameraCamera2 = "1.2.3"
coilSvg = "2.2.2"
composeStateEvents = "1.2.3"
composedBarcodes = "1.1.1"
constraintlayout = "2.1.4"
converterMoshi = "2.9.0"
coilCompose = "2.3.0"
coreSplashscreen = "1.0.1"
creativekit = "2.1.0"
datastorePreferences = "1.0.0"
espressoCore = "3.5.1"
firebaseAppcheckDebug = "17.0.1"
gradle = "8.0.2"
grpcOkhttp = "1.52.1"
grpcProtobufLite = "1.52.1"
grpcStub = "1.52.1"
grpcKotlinStub = "1.3.0"
hiltAndroidCompiler = "2.44"
hiltCompiler = "1.0.0"
hiltNavigationCompose = "1.0.0"
hiltAndroid = "2.44.2"
hiltWork = "1.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
klaxon = "5.5"
kotlinxCoroutinesPlayServices = "1.7.2"
kotlinxSerializationJson = "1.3.3"
lifecycleExtensions = "2.2.0"
lifecycleLivedataKtx = "2.6.1"
loginkit = "2.1.0"
mapboxSearchAndroid = "1.0.0-beta.43"
mapboxSdkServices = "6.11.0"
material = "1.9.0"
moshiKotlinCodegen = "1.14.0"
moshi = "1.14.0"
materialIconsExtended = "1.5.0"
materialIconsCore = "1.5.0"
pagingCompose = "3.2.0"
pagingRuntimeKtx = "3.2.0"
playServicesAds = "22.2.0"
playServicesAuth = "20.6.0"
playServicesLocation = "21.0.1"
playServicesMaps = "18.1.0"
roomPaging = "2.5.2"
roomKtx = "2.5.2"
roomCompiler = "2.5.2"
roomRuntime = "2.5.2"
retrofit = "2.9.0"
symbolProcessingApi = "1.8.20-1.0.11"
uiTestManifest = "1.5.0"
uiTooling = "1.5.0"
uiTestJunit4 = "1.5.0"
kotlin = "1.8.20"
ksp = "1.8.20-1.0.11"
protobuf = "3.23.0"
protobufPlugin = "0.9.3"
gmsPlugin = "4.3.14"
firebaseCrashlyticsPlugin = "2.9.8"
firebasePerfPlugin = "1.4.2"
userMessagingPlatform = "2.1.0"
workMultiprocess = "2.8.1"
workRuntimeKtx = "2.8.1"
org-jetbrains-kotlin-jvm = "1.8.20"

[libraries]
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometricKtx" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_converter_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
android = { module = "com.mapbox.maps:android", version.ref = "android" }
androidx-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "animationGraphics" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPagerIndicators" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanistPlaceholderMaterial" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanistNavigationMaterial" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "annotationsApi" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coilSvg" }
compose-state-events = { module = "com.github.leonard-palm:compose-state-events", version.ref = "composeStateEvents" }
composed-barcodes = { module = "com.simonsickle:composed-barcodes", version.ref = "composedBarcodes" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycleRuntimeKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
creativekit = { module = "com.snap.creativekit:creativekit", version.ref = "creativekit" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug", version.ref = "firebaseAppcheckDebug" }
firebase-bom = { module = "com.google.firebase:firebase-bom", name = "firebase-bom", version.ref = "firebaseBom" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpcProtobufLite" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpcStub" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlinStub" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycleRuntimeKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
junit = { module = "junit:junit", version.ref = "junit" }
klaxon = { module = "com.beust:klaxon", version.ref = "klaxon" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
loginkit = { module = "com.snap.loginkit:loginkit", version.ref = "loginkit" }
mapbox-search-android = { module = "com.mapbox.search:mapbox-search-android", version.ref = "mapboxSearchAndroid" }
mapbox-sdk-services = { module = "com.mapbox.mapboxsdk:mapbox-sdk-services", version.ref = "mapboxSdkServices" }
material = { module = "com.google.android.material:material", version.ref = "material" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
